#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)

test -f "$ROOT_DIR/SECURITY.md"
test -f "$ROOT_DIR/CODE_OF_CONDUCT.md"
test -f "$ROOT_DIR/CHANGELOG.md"
test -f "$ROOT_DIR/ROADMAP.md"
test -f "$ROOT_DIR/references/architecture.md"
test -f "$ROOT_DIR/references/release-checklist.md"
test -f "$ROOT_DIR/.github/release-template.md"
test -f "$ROOT_DIR/.github/workflows/ci.yml"
test -f "$ROOT_DIR/tools/bin/render-dashboard-demo-media.sh"
test -f "$ROOT_DIR/tools/bin/render-architecture-infographics.sh"
test -f "$ROOT_DIR/tools/architecture/architecture-infographics.html"
test -f "$ROOT_DIR/assets/readme/dashboard-demo.png"
test -f "$ROOT_DIR/assets/readme/dashboard-demo.gif"
test -f "$ROOT_DIR/assets/architecture/agent-control-plane-architecture.pdf"
test -f "$ROOT_DIR/assets/architecture/overview-infographic.png"
test -f "$ROOT_DIR/assets/architecture/runtime-loop-infographic.png"
test -f "$ROOT_DIR/assets/architecture/worker-lifecycle-infographic.png"
test -f "$ROOT_DIR/assets/architecture/state-dashboard-infographic.png"

grep -q 'Use GitHub private vulnerability reporting or a GitHub security advisory' "$ROOT_DIR/SECURITY.md"
grep -q 'For undisclosed security issues, use \[SECURITY.md\](\./SECURITY.md)' "$ROOT_DIR/CODE_OF_CONDUCT.md"
grep -q '^## \[Unreleased\]$' "$ROOT_DIR/CHANGELOG.md"
grep -q '^## \[0.1.0\] - 2026-03-27$' "$ROOT_DIR/CHANGELOG.md"
grep -q '^# Roadmap$' "$ROOT_DIR/ROADMAP.md"
grep -q '^## Platform Support$' "$ROOT_DIR/ROADMAP.md"
grep -q '^| Platform | Status | Why it matters next |$' "$ROOT_DIR/ROADMAP.md"
grep -q '^| `macOS` | best supported today | Current reference platform for setup, launchd, dashboard, and local operator flows\. |$' "$ROOT_DIR/ROADMAP.md"
grep -q '^| `Linux` | planned next | ACP already knows common Linux package managers; the missing step is first-class runtime/service validation and an operator story as smooth as macOS\. |$' "$ROOT_DIR/ROADMAP.md"
grep -q '^| `Windows (WSL2)` | exploratory next | A practical bridge for Windows users who still want Unix-like repos, containers, and worker CLIs\. |$' "$ROOT_DIR/ROADMAP.md"
grep -q '^| `Native Windows` | longer-term | Needs explicit work around services, shell/process management, path handling, and backend compatibility\. |$' "$ROOT_DIR/ROADMAP.md"
grep -q '^| Backend | Status | Runtime Routing | Profile Scaffolding | Notes |$' "$ROOT_DIR/ROADMAP.md"
grep -q '^| `codex` | available now | yes | yes | First-class worker path for Codex-backed runs\. |$' "$ROOT_DIR/ROADMAP.md"
grep -q '^| `opencode` | planned next | placeholder scaffold | no | Adapter stub ships in the package, but live execution is not implemented yet\. |$' "$ROOT_DIR/ROADMAP.md"
grep -q '^| `kilo` | planned next | placeholder scaffold | no | Adapter stub ships in the package, but live execution is not implemented yet\. |$' "$ROOT_DIR/ROADMAP.md"
grep -q '^| `gemini-cli` | research next | no | no | Official Google terminal agent and the closest ecosystem fit for a future ACP worker adapter\. |$' "$ROOT_DIR/ROADMAP.md"
grep -q -- '- `codex`' "$ROOT_DIR/ROADMAP.md"
grep -q -- '- `claude`' "$ROOT_DIR/ROADMAP.md"
grep -q -- '- `openclaw`' "$ROOT_DIR/ROADMAP.md"
grep -q -- '- `opencode`' "$ROOT_DIR/ROADMAP.md"
grep -q -- '- `kilo`' "$ROOT_DIR/ROADMAP.md"
grep -q -- '- `gemini-cli`' "$ROOT_DIR/ROADMAP.md"
grep -q '^## Adjacent Runtime and Model Integrations$' "$ROOT_DIR/ROADMAP.md"
grep -q '^| Target | Category | Status | Why it matters |$' "$ROOT_DIR/ROADMAP.md"
grep -q '^| `ollama` | local model runtime | research next | Strong local-first story, cross-platform distribution, and an existing tool-launch surface that already knows about coding tools\. |$' "$ROOT_DIR/ROADMAP.md"
grep -q '^| `nanoclaw` | containerized assistant runtime | exploratory | Useful reference for container isolation, scheduled tasks, and WSL2-friendly workflows around Claude-powered agents\. |$' "$ROOT_DIR/ROADMAP.md"
grep -q '^| `picoclaw` | lightweight assistant runtime | exploratory | Interesting for Linux and edge-style deployments, MCP-heavy workflows, and ultra-low-footprint automation\. |$' "$ROOT_DIR/ROADMAP.md"
grep -q '^# Release Summary$' "$ROOT_DIR/.github/release-template.md"
grep -q '\[SECURITY.md\](\./SECURITY.md)' "$ROOT_DIR/README.md"
grep -q '\[CODE_OF_CONDUCT.md\](\./CODE_OF_CONDUCT.md)' "$ROOT_DIR/README.md"
grep -q '\[CHANGELOG.md\](\./CHANGELOG.md)' "$ROOT_DIR/README.md"
grep -q '\[ROADMAP.md\](\./ROADMAP.md)' "$ROOT_DIR/README.md"
grep -q '\[references/architecture.md\](\./references/architecture.md)' "$ROOT_DIR/README.md"
grep -q '\[references/commands.md\](\./references/commands.md)' "$ROOT_DIR/README.md"
grep -q 'keep coding agents running reliably without' "$ROOT_DIR/README.md"
grep -q 'constant human babysitting' "$ROOT_DIR/README.md"
grep -q 'replace human babysitting with boring runtime ownership: supervisor,' "$ROOT_DIR/README.md"
grep -q '^## Architecture$' "$ROOT_DIR/README.md"
grep -q '^### Runtime Loop At A Glance$' "$ROOT_DIR/README.md"
grep -q '```mermaid' "$ROOT_DIR/README.md"
grep -q '\[System overview\](\./references/architecture.md#system-overview)' "$ROOT_DIR/README.md"
grep -q '\[Runtime scheduler loop\](\./references/architecture.md#runtime-scheduler-loop)' "$ROOT_DIR/README.md"
grep -q '\[Dashboard snapshot pipeline\](\./references/architecture.md#dashboard-snapshot-pipeline)' "$ROOT_DIR/README.md"
grep -q '\[Architecture deck PDF\](\./assets/architecture/agent-control-plane-architecture.pdf)' "$ROOT_DIR/README.md"
grep -q '\[Overview infographic\](\./assets/architecture/overview-infographic.png)' "$ROOT_DIR/README.md"
grep -q '\[Runtime loop infographic\](\./assets/architecture/runtime-loop-infographic.png)' "$ROOT_DIR/README.md"
grep -q '\[Worker lifecycle infographic\](\./assets/architecture/worker-lifecycle-infographic.png)' "$ROOT_DIR/README.md"
grep -q '\[State and dashboard infographic\](\./assets/architecture/state-dashboard-infographic.png)' "$ROOT_DIR/README.md"
grep -q 'planned next: `opencode`, `kilo`, `gemini-cli`' "$ROOT_DIR/README.md"
grep -q 'platform roadmap now calls out Linux, Windows via WSL2, and the longer-term' "$ROOT_DIR/README.md"
grep -q 'native Windows story explicitly' "$ROOT_DIR/README.md"
grep -q 'such as `ollama`, `nanoclaw`, and `picoclaw`' "$ROOT_DIR/README.md"
grep -q 'roadmap matrix now distinguishes implemented backends from placeholder' "$ROOT_DIR/README.md"
grep -q '^### Backend Snapshot$' "$ROOT_DIR/README.md"
grep -q '^| Backend | What You Can Expect Today |$' "$ROOT_DIR/README.md"
grep -q '^| `codex` | Ready for real ACP workflows today\. |$' "$ROOT_DIR/README.md"
grep -q '^| `openclaw` | Ready for real ACP workflows today, including resident-style runs\. |$' "$ROOT_DIR/README.md"
grep -q '^| `opencode` | Scaffolded in the package so routing and docs can evolve, but not implemented for live execution yet\. |$' "$ROOT_DIR/README.md"
grep -q '^| `kilo` | Scaffolded in the package so routing and docs can evolve, but not implemented for live execution yet\. |$' "$ROOT_DIR/README.md"
grep -q '^| `gemini-cli` | Not wired into ACP yet, but on the public roadmap as a strong future worker candidate\. |$' "$ROOT_DIR/README.md"
grep -q '^### Support Matrix$' "$ROOT_DIR/README.md"
grep -q '^| Target | Kind | ACP Relationship Today | Current Status |$' "$ROOT_DIR/README.md"
grep -q '^| `codex` | direct worker | First-class ACP worker backend | production-ready path today |$' "$ROOT_DIR/README.md"
grep -q '^| `openclaw` | direct worker | First-class ACP worker backend with resident workflow support | production-ready path today |$' "$ROOT_DIR/README.md"
grep -q '^| `gemini-cli` | direct worker | Research target for a future worker adapter | roadmap candidate |$' "$ROOT_DIR/README.md"
grep -q '^| `ollama` | local model runtime | Candidate local-model substrate behind future ACP integrations | research target |$' "$ROOT_DIR/README.md"
grep -q '^| `nanoclaw` | adjacent agent shell | Ecosystem reference for containerized and WSL2-friendly workflows | exploratory interoperability target |$' "$ROOT_DIR/README.md"
grep -q '^| `picoclaw` | adjacent agent shell | Ecosystem reference for lightweight Linux and edge-style agent runtimes | exploratory interoperability target |$' "$ROOT_DIR/README.md"
grep -q 'If you are trying ACP on a real repo right now, start with `codex`, `claude`,' "$ROOT_DIR/README.md"
grep -q 'img.shields.io/badge/ci-local%20smoke-1f6feb' "$ROOT_DIR/README.md"
grep -q 'img.shields.io/badge/version-0.1.0-2da44e' "$ROOT_DIR/README.md"
grep -q 'img.shields.io/badge/node-%3E%3D18-339933' "$ROOT_DIR/README.md"
grep -q 'img.shields.io/badge/license-MIT-2da44e' "$ROOT_DIR/README.md"
grep -q '\./\.github/workflows/ci.yml' "$ROOT_DIR/README.md"
grep -q '\./CHANGELOG.md' "$ROOT_DIR/README.md"
grep -q '\./package.json' "$ROOT_DIR/README.md"
grep -q '\./assets/readme/dashboard-demo.png' "$ROOT_DIR/README.md"
grep -q '\./assets/readme/dashboard-demo.gif' "$ROOT_DIR/README.md"
grep -q '^| Tool | Required | Why ACP uses it | Notes |$' "$ROOT_DIR/README.md"
grep -q '^| Node.js `>= 18` | yes | Runs the npm package entrypoint and `npx agent-control-plane \.\.\.` wrapper\. |' "$ROOT_DIR/README.md"
grep -q '^| `jq` | yes | Several runtime and GitHub flows parse JSON from `gh` and worker metadata\. |' "$ROOT_DIR/README.md"
grep -q '^| Bundled `codex-quota` plus ACP quota manager | automatic for Codex profiles | Improves Codex quota-aware failover and health signals\. |' "$ROOT_DIR/README.md"
grep -q 'ACP_CODEX_QUOTA_BIN=/path/to/codex-quota' "$ROOT_DIR/README.md"
grep -q '^| Command | What it is for | Key args and parameters |$' "$ROOT_DIR/README.md"
grep -q '^```bash$' "$ROOT_DIR/README.md"
grep -q '^npx agent-control-plane@latest setup$' "$ROOT_DIR/README.md"
grep -q '`setup` detects the current repo when it can' "$ROOT_DIR/README.md"
grep -q 'offers to install missing core tools' "$ROOT_DIR/README.md"
grep -q 'can prompt to run `gh auth login`' "$ROOT_DIR/README.md"
grep -q 'reports core tool and auth readiness' "$ROOT_DIR/README.md"
grep -q '^During `setup`, ACP can:$' "$ROOT_DIR/README.md"
grep -q 'supported package managers such as `brew`, `apt-get`, `dnf`, `yum`,' "$ROOT_DIR/README.md"
grep -q 'offer to install supported worker backends like `codex`, `claude`, or' "$ROOT_DIR/README.md"
grep -q 'run one final fix-up summary at the end so you can clear whatever is still' "$ROOT_DIR/README.md"
grep -q 'The wizard now automates ACP'\''s shell/runtime prerequisites and can also' "$ROOT_DIR/README.md"
grep -q 'auto-install supported worker CLIs through npm' "$ROOT_DIR/README.md"
grep -q 'it will tell you what is missing, print' "$ROOT_DIR/README.md"
grep -q 'backend-specific next steps, and offer to open the right setup docs' "$ROOT_DIR/README.md"
grep -q '^npx agent-control-plane@latest setup --dry-run$' "$ROOT_DIR/README.md"
grep -q 'without writing files, installing packages, or launching background services' "$ROOT_DIR/README.md"
grep -q 'emit exactly one JSON object on `stdout`' "$ROOT_DIR/README.md"
grep -q 'send progress logs to' "$ROOT_DIR/README.md"
grep -q '`stderr`, which keeps parsing stable\.' "$ROOT_DIR/README.md"
grep -q '`--non-interactive`, `--install-missing-deps`, `--gh-auth-login`,' "$ROOT_DIR/README.md"
grep -q '`--start-runtime`, and `--json`\.' "$ROOT_DIR/README.md"
grep -q '^| `npx agent-control-plane@latest setup` | Guided bootstrap for one repo profile\. |' "$ROOT_DIR/README.md"
grep -q 'can install missing core tools, supported worker backends, and run `gh auth login`' "$ROOT_DIR/README.md"
grep -q 'Add `--json` for one structured JSON result on `stdout`' "$ROOT_DIR/README.md"
grep -q '^| `npx agent-control-plane@latest setup --dry-run` | Preview exactly what setup would do without changing the machine\. |' "$ROOT_DIR/README.md"
grep -q 'Add `--json` for a machine-readable plan object\.' "$ROOT_DIR/README.md"
grep -q '^| `npx agent-control-plane@latest install` | Alias for `sync`\.' "$ROOT_DIR/README.md"
grep -q '^| `npx agent-control-plane@latest runtime <status\|start\|stop\|restart> --profile-id <id>` | Operate one profile runtime\. |' "$ROOT_DIR/README.md"
grep -q '\[references/commands.md\](\./references/commands.md)' "$ROOT_DIR/README.md"
grep -q '^# Architecture Guide$' "$ROOT_DIR/references/architecture.md"
grep -q '^## System Overview$' "$ROOT_DIR/references/architecture.md"
grep -q '^## Install and Publication Flow$' "$ROOT_DIR/references/architecture.md"
grep -q '^## Runtime Scheduler Loop$' "$ROOT_DIR/references/architecture.md"
grep -q '^## Worker Session Lifecycle$' "$ROOT_DIR/references/architecture.md"
grep -q '^## Dashboard Snapshot Pipeline$' "$ROOT_DIR/references/architecture.md"
grep -q '```mermaid' "$ROOT_DIR/references/architecture.md"
grep -q 'Maintainer checklist for shipping a new public package release' "$ROOT_DIR/references/release-checklist.md"
grep -q 'npm publish --access public' "$ROOT_DIR/references/release-checklist.md"
grep -q 'render-dashboard-demo-media.sh' "$ROOT_DIR/references/release-checklist.md"
grep -q 'if a public GitHub repo now exists, set or verify the `homepage`,' "$ROOT_DIR/references/release-checklist.md"
grep -q '`repository`, and `bugs` URLs in `package.json`' "$ROOT_DIR/references/release-checklist.md"
grep -q 'bash tools/bin/test-smoke.sh' "$ROOT_DIR/references/release-checklist.md"
grep -q '`references/release-checklist.md`' "$ROOT_DIR/references/docs-map.md"
grep -q '`references/architecture.md`' "$ROOT_DIR/references/docs-map.md"
grep -q '`CHANGELOG.md`' "$ROOT_DIR/references/docs-map.md"
grep -q '`ROADMAP.md`' "$ROOT_DIR/references/docs-map.md"
grep -q '`.github/release-template.md`' "$ROOT_DIR/references/docs-map.md"
grep -q '`.github/workflows/ci.yml`' "$ROOT_DIR/references/docs-map.md"
grep -q '`tools/bin/render-dashboard-demo-media.sh`' "$ROOT_DIR/references/docs-map.md"
grep -q '`tools/bin/render-architecture-infographics.sh`' "$ROOT_DIR/references/docs-map.md"

echo "public repo docs test passed"
