#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)

test -f "$ROOT_DIR/SECURITY.md"
test -f "$ROOT_DIR/CODE_OF_CONDUCT.md"
test -f "$ROOT_DIR/CHANGELOG.md"
test -f "$ROOT_DIR/ROADMAP.md"
test -f "$ROOT_DIR/references/architecture.md"
test -f "$ROOT_DIR/references/release-checklist.md"
test -f "$ROOT_DIR/.github/release-template.md"
test -f "$ROOT_DIR/.github/workflows/ci.yml"
test -f "$ROOT_DIR/.github/workflows/publish.yml"
test -f "$ROOT_DIR/tools/bin/render-dashboard-demo-media.sh"
test -f "$ROOT_DIR/tools/bin/render-architecture-infographics.sh"
test -f "$ROOT_DIR/tools/architecture/architecture-infographics.html"
test -f "$ROOT_DIR/assets/readme/dashboard-demo.png"
test -f "$ROOT_DIR/assets/architecture/agent-control-plane-architecture.pdf"
test -f "$ROOT_DIR/assets/architecture/overview-infographic.png"
test -f "$ROOT_DIR/assets/architecture/runtime-loop-infographic.png"
test -f "$ROOT_DIR/assets/architecture/worker-lifecycle-infographic.png"
test -f "$ROOT_DIR/assets/architecture/state-dashboard-infographic.png"

grep -q 'Use GitHub private vulnerability reporting or a GitHub security advisory' "$ROOT_DIR/SECURITY.md"
grep -q 'For undisclosed security issues, use \[SECURITY.md\](\./SECURITY.md)' "$ROOT_DIR/CODE_OF_CONDUCT.md"
grep -q '^## \[Unreleased\]$' "$ROOT_DIR/CHANGELOG.md"
grep -q '^## \[0.1.4\] - 2026-03-30$' "$ROOT_DIR/CHANGELOG.md"
grep -q '^## \[0.1.3\] - 2026-03-30$' "$ROOT_DIR/CHANGELOG.md"
grep -q '^## \[0.1.2\] - 2026-03-30$' "$ROOT_DIR/CHANGELOG.md"
grep -q '^## \[0.1.1\] - 2026-03-30$' "$ROOT_DIR/CHANGELOG.md"
grep -q '^## \[0.1.0\] - 2026-03-27$' "$ROOT_DIR/CHANGELOG.md"
grep -q '^# Roadmap$' "$ROOT_DIR/ROADMAP.md"
grep -q '^## Platform Support$' "$ROOT_DIR/ROADMAP.md"
grep -q '^| Platform | Status | Why it matters next |$' "$ROOT_DIR/ROADMAP.md"
grep -q '^| `macOS` | best supported today | Current reference platform for setup, launchd, dashboard, and local operator flows\. |$' "$ROOT_DIR/ROADMAP.md"
grep -q '^| `Linux` | planned next | ACP already knows common Linux package managers; the missing step is first-class runtime/service validation and an operator story as smooth as macOS\. |$' "$ROOT_DIR/ROADMAP.md"
grep -q '^| `Windows (WSL2)` | exploratory next | A practical bridge for Windows users who still want Unix-like repos, containers, and worker CLIs\. |$' "$ROOT_DIR/ROADMAP.md"
grep -q '^| `Native Windows` | longer-term | Needs explicit work around services, shell/process management, path handling, and backend compatibility\. |$' "$ROOT_DIR/ROADMAP.md"
grep -q '^| Backend | Status | Runtime Routing | Profile Scaffolding | Notes |$' "$ROOT_DIR/ROADMAP.md"
grep -q '^| `codex` | production-ready | yes | yes |' "$ROOT_DIR/ROADMAP.md"
grep -q '^| `opencode` | experimental | yes | yes |' "$ROOT_DIR/ROADMAP.md"
grep -q '^| `kilo` | experimental | yes | yes |' "$ROOT_DIR/ROADMAP.md"
grep -q '^| `gemini-cli` | research next | no | no |' "$ROOT_DIR/ROADMAP.md"
grep -q -- '- `codex`' "$ROOT_DIR/ROADMAP.md"
grep -q -- '- `claude`' "$ROOT_DIR/ROADMAP.md"
grep -q -- '- `openclaw`' "$ROOT_DIR/ROADMAP.md"
grep -q -- '- `opencode`' "$ROOT_DIR/ROADMAP.md"
grep -q -- '- `kilo`' "$ROOT_DIR/ROADMAP.md"
grep -q -- '- `gemini-cli`' "$ROOT_DIR/ROADMAP.md"
grep -q '^## Adjacent Runtime and Model Integrations$' "$ROOT_DIR/ROADMAP.md"
grep -q '^| Target | Category | Status | Why it matters |$' "$ROOT_DIR/ROADMAP.md"
grep -q '^| `ollama` | local model runtime | \*\*integrated\*\* |' "$ROOT_DIR/ROADMAP.md"
grep -q '^| `nanoclaw` | containerized assistant runtime | exploratory | Useful reference for container isolation, scheduled tasks, and WSL2-friendly workflows around Claude-powered agents\. |$' "$ROOT_DIR/ROADMAP.md"
grep -q '^| `picoclaw` | lightweight assistant runtime | exploratory | Interesting for Linux and edge-style deployments, MCP-heavy workflows, and ultra-low-footprint automation\. |$' "$ROOT_DIR/ROADMAP.md"
grep -q '^# Release Summary$' "$ROOT_DIR/.github/release-template.md"
grep -q '^name: Publish$' "$ROOT_DIR/.github/workflows/publish.yml"
grep -q 'id-token: write' "$ROOT_DIR/.github/workflows/publish.yml"
grep -q 'npm publish --provenance --access public' "$ROOT_DIR/.github/workflows/publish.yml"
grep -q 'git describe --tags --exact-match' "$ROOT_DIR/.github/workflows/publish.yml"
grep -q '\[SECURITY.md\](\./SECURITY.md)' "$ROOT_DIR/README.md"
grep -q '\[CODE_OF_CONDUCT.md\](\./CODE_OF_CONDUCT.md)' "$ROOT_DIR/README.md"
grep -q '\[CHANGELOG.md\](\./CHANGELOG.md)' "$ROOT_DIR/README.md"
grep -q '\[ROADMAP.md\](\./ROADMAP.md)' "$ROOT_DIR/README.md"
grep -q '\[references/architecture.md\](\./references/architecture.md)' "$ROOT_DIR/README.md"
grep -q '\[references/commands.md\](\./references/commands.md)' "$ROOT_DIR/README.md"
grep -q 'keeps your coding agents running reliably without' "$ROOT_DIR/README.md"
grep -q 'you having to stare at them all day' "$ROOT_DIR/README.md"
grep -q '^## Architecture$' "$ROOT_DIR/README.md"
grep -q '^### Runtime Loop At A Glance$' "$ROOT_DIR/README.md"
grep -q '```mermaid' "$ROOT_DIR/README.md"
grep -q '\[System overview\](\./references/architecture.md#system-overview)' "$ROOT_DIR/README.md"
grep -q '\[Runtime scheduler loop\](\./references/architecture.md#runtime-scheduler-loop)' "$ROOT_DIR/README.md"
grep -q '\[Dashboard snapshot pipeline\](\./references/architecture.md#dashboard-snapshot-pipeline)' "$ROOT_DIR/README.md"
grep -q '\[Architecture deck PDF\](\./assets/architecture/agent-control-plane-architecture.pdf)' "$ROOT_DIR/README.md"
grep -q '\[Overview infographic\](\./assets/architecture/overview-infographic.png)' "$ROOT_DIR/README.md"
grep -q '\[Runtime loop infographic\](\./assets/architecture/runtime-loop-infographic.png)' "$ROOT_DIR/README.md"
grep -q '\[Worker lifecycle infographic\](\./assets/architecture/worker-lifecycle-infographic.png)' "$ROOT_DIR/README.md"
grep -q '\[State and dashboard infographic\](\./assets/architecture/state-dashboard-infographic.png)' "$ROOT_DIR/README.md"
grep -q '^## Roadmap$' "$ROOT_DIR/README.md"
grep -q '^### Backend Status$' "$ROOT_DIR/README.md"
grep -q '^| Backend | Status | Notes |$' "$ROOT_DIR/README.md"
grep -q '^| `codex` | Production-ready |' "$ROOT_DIR/README.md"
grep -q '^| `openclaw` | Production-ready |' "$ROOT_DIR/README.md"
grep -q '^| `opencode` | Experimental |' "$ROOT_DIR/README.md"
grep -q '^| `kilo` | Experimental |' "$ROOT_DIR/README.md"
grep -q '^| `gemini-cli` | Roadmap |' "$ROOT_DIR/README.md"
grep -q '^| `ollama` | Experimental |' "$ROOT_DIR/README.md"
grep -q '^| `nanoclaw` | Exploratory | Ecosystem reference for containerized and WSL2-friendly workflows\. |$' "$ROOT_DIR/README.md"
grep -q '^| `picoclaw` | Exploratory | Ecosystem reference for lightweight Linux and edge-style runtimes\. |$' "$ROOT_DIR/README.md"
grep -q 'If you are trying ACP on a real repo right now, start with `codex`, `claude`,' "$ROOT_DIR/README.md"
grep -q 'github.com/ducminhnguyen0319/agent-control-plane/actions/workflows/ci.yml/badge.svg?branch=main' "$ROOT_DIR/README.md"
grep -q 'img.shields.io/npm/v/agent-control-plane' "$ROOT_DIR/README.md"
grep -q 'img.shields.io/node/v/agent-control-plane' "$ROOT_DIR/README.md"
grep -q 'img.shields.io/npm/l/agent-control-plane' "$ROOT_DIR/README.md"
grep -q 'https://socket.dev/npm/package/agent-control-plane' "$ROOT_DIR/README.md"
grep -q 'img.shields.io/badge/Socket-79-f5a623' "$ROOT_DIR/README.md"
grep -q 'https://github.com/ducminhnguyen0319/agent-control-plane/actions/workflows/ci.yml' "$ROOT_DIR/README.md"
grep -q 'https://www.npmjs.com/package/agent-control-plane' "$ROOT_DIR/README.md"
grep -q '\./assets/readme/dashboard-demo.png' "$ROOT_DIR/README.md"
grep -q '^| Tool | Required | Purpose | Notes |$' "$ROOT_DIR/README.md"
grep -q '^| Node.js `>= 18` | yes | Runs the npm package entrypoint and `npx` wrapper\. |' "$ROOT_DIR/README.md"
grep -q '^| `jq` | yes | Parses JSON from `gh` output and worker metadata throughout\. |' "$ROOT_DIR/README.md"
grep -q '^| Bundled `codex-quota` + ACP quota manager | automatic for Codex | Quota-aware failover and health signals for Codex profiles\. |' "$ROOT_DIR/README.md"
grep -q 'ACP_CODEX_QUOTA_BIN' "$ROOT_DIR/README.md"
grep -q '^| Command | Purpose |$' "$ROOT_DIR/README.md"
grep -q '^```bash$' "$ROOT_DIR/README.md"
grep -q '^npx agent-control-plane@latest setup$' "$ROOT_DIR/README.md"
grep -q 'The wizard walks you through the full setup in one pass' "$ROOT_DIR/README.md"
grep -q '^npx agent-control-plane@latest setup --dry-run$' "$ROOT_DIR/README.md"
grep -q 'To preview exactly what it would do before touching anything:' "$ROOT_DIR/README.md"
grep -q 'With `--json`, ACP emits a single structured object on `stdout`' "$ROOT_DIR/README.md"
grep -q 'progress logs to `stderr`, which keeps parsing stable\.' "$ROOT_DIR/README.md"
grep -q '^  --non-interactive \\' "$ROOT_DIR/README.md"
grep -q '^  --install-missing-deps \\' "$ROOT_DIR/README.md"
grep -q '^  --start-runtime \\' "$ROOT_DIR/README.md"
grep -q '  --json' "$ROOT_DIR/README.md"
grep -q '^| `setup \[--dry-run\] \[--json\]` | Guided bootstrap wizard\.' "$ROOT_DIR/README.md"
grep -q '^| `sync` / `install` | Stage or refresh the packaged runtime into `~/.agent-runtime/runtime-home`\. Run after install or upgrade\. |$' "$ROOT_DIR/README.md"
grep -q '^| `runtime <status\\|start\\|stop\\|restart> --profile-id <id>` | Operate one profile runtime\. |$' "$ROOT_DIR/README.md"
grep -q '\[references/commands.md\](\./references/commands.md)' "$ROOT_DIR/README.md"
grep -q '^# Architecture Guide$' "$ROOT_DIR/references/architecture.md"
grep -q '^## System Overview$' "$ROOT_DIR/references/architecture.md"
grep -q '^## Install and Publication Flow$' "$ROOT_DIR/references/architecture.md"
grep -q '^## Runtime Scheduler Loop$' "$ROOT_DIR/references/architecture.md"
grep -q '^## Worker Session Lifecycle$' "$ROOT_DIR/references/architecture.md"
grep -q '^## Dashboard Snapshot Pipeline$' "$ROOT_DIR/references/architecture.md"
grep -q '```mermaid' "$ROOT_DIR/references/architecture.md"
grep -q 'Maintainer checklist for shipping a new public package release' "$ROOT_DIR/references/release-checklist.md"
grep -q 'trusted publishing from GitHub Actions' "$ROOT_DIR/references/release-checklist.md"
grep -q '\.github/workflows/publish.yml' "$ROOT_DIR/references/release-checklist.md"
grep -q 'git push origin main --follow-tags' "$ROOT_DIR/references/release-checklist.md"
grep -q 'npm package shows provenance' "$ROOT_DIR/references/release-checklist.md"
grep -q 'if a public GitHub repo now exists, set or verify the `homepage`,' "$ROOT_DIR/references/release-checklist.md"
grep -q '`repository`, and `bugs` URLs in `package.json`' "$ROOT_DIR/references/release-checklist.md"
grep -q 'bash tools/bin/test-smoke.sh' "$ROOT_DIR/references/release-checklist.md"
grep -q '`references/release-checklist.md`' "$ROOT_DIR/references/docs-map.md"
grep -q '`references/architecture.md`' "$ROOT_DIR/references/docs-map.md"
grep -q '`CHANGELOG.md`' "$ROOT_DIR/references/docs-map.md"
grep -q '`ROADMAP.md`' "$ROOT_DIR/references/docs-map.md"
grep -q '`.github/release-template.md`' "$ROOT_DIR/references/docs-map.md"
grep -q '`.github/workflows/ci.yml`' "$ROOT_DIR/references/docs-map.md"
grep -q '`.github/workflows/publish.yml`' "$ROOT_DIR/references/docs-map.md"
grep -q '`tools/bin/render-dashboard-demo-media.sh`' "$ROOT_DIR/references/docs-map.md"
grep -q '`tools/bin/render-architecture-infographics.sh`' "$ROOT_DIR/references/docs-map.md"

echo "public repo docs test passed"
